namespace Excelsior.SourceGenerator;

[Generator]
public class SheetBuilderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                "Excelsior.SheetModelAttribute",
                (node, _) => node is TypeDeclarationSyntax,
                (context, _) => GetModelInfo(context));

        context.RegisterSourceOutput(
            models,
            (productionContext, model) =>
            {
                if (model is null)
                {
                    return;
                }

                var source = GenerateSource(model.Value);
                productionContext.AddSource($"{model.Value.TypeName}SheetBuilderExtensions.g.cs", source);
            });
    }

    static ModelInfo? GetModelInfo(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var properties = new EquatableArray<PropertyInfo>(GetProperties(type).ToImmutableArray());

        if (properties.Length == 0)
        {
            return null;
        }

        return new ModelInfo(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            properties);
    }

    static IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol type) =>
        GetPropertiesRecursive(type, ImmutableArray<string>.Empty);

    static IEnumerable<PropertyInfo> GetPropertiesRecursive(INamedTypeSymbol type, ImmutableArray<string> parentPath)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol property)
            {
                continue;
            }

            if (property.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (property.GetMethod is null)
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.IgnoreAttribute"))
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.SplitAttribute") ||
                HasAttribute(property.Type, "Excelsior.SplitAttribute"))
            {
                if (property.Type is INamedTypeSymbol namedType)
                {
                    var newPath = parentPath.Add(property.Name);
                    foreach (var nested in GetPropertiesRecursive(namedType, newPath))
                    {
                        yield return nested;
                    }
                }

                continue;
            }

            var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var accessPath = parentPath.IsEmpty
                ? property.Name
                : string.Join(".", parentPath.Add(property.Name));

            yield return new(property.Name, propertyType, accessPath);
        }
    }

    static bool HasAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(_ => _.AttributeClass?.ToDisplayString() == fullName);

    static bool HasAttribute(ITypeSymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(_ => _.AttributeClass?.ToDisplayString() == fullName);

    static string GenerateSource(ModelInfo model)
    {
        var builder = new StringBuilder(
            $$"""
              // <auto-generated/>
              #nullable enable
              namespace Excelsior;
              using System;
              public static class {{model.TypeName}}SheetBuilderExtensions
              {

              """);

        for (var i = 0; i < model.Properties.Array.Length; i++)
        {
            if (i > 0)
            {
                builder.AppendLine();
            }

            var (prefix, propType, access) = model.Properties[i];
            var modelType = model.TypeFullName;

            builder.Append(
                $"""
                     public static ISheetBuilder<{modelType}, TStyle> {prefix}Column<TStyle>(
                         this ISheetBuilder<{modelType}, TStyle> builder,
                         Action<ColumnConfig<TStyle, {modelType}, {propType}>> configuration)
                         => builder.Column(_ => _.{access}, configuration);

                     public static void {prefix}HeadingText<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)
                         => builder.HeadingText(_ => _.{access}, value);

                     public static void {prefix}Order<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)
                         => builder.Order(_ => _.{access}, value);

                     public static void {prefix}Width<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)
                         => builder.Width(_ => _.{access}, value);

                     public static void {prefix}HeadingStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, Action<TStyle> value)
                         => builder.HeadingStyle(_ => _.{access}, value);

                     public static void {prefix}CellStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, Action<TStyle, {modelType}, {propType}> value)
                         => builder.CellStyle(_ => _.{access}, value);

                     public static void {prefix}Format<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)
                         => builder.Format(_ => _.{access}, value);

                     public static void {prefix}NullDisplay<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)
                         => builder.NullDisplay(_ => _.{access}, value);

                     public static void {prefix}IsHtml<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)
                         => builder.IsHtml(_ => _.{access});

                     public static void {prefix}Render<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, Func<{modelType}, {propType}, string?> value)
                         => builder.Render(_ => _.{access}, value);

                     public static void {prefix}Filter<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)
                         => builder.Filter(_ => _.{access});

                 """);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }
}
