using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Excelsior.SourceGenerator;

[Generator]
public class SheetBuilderExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Excelsior.ExcelsiorModelAttribute",
            (node, _) => node is TypeDeclarationSyntax,
            (ctx, _) => GetModelInfo(ctx));

        context.RegisterSourceOutput(models, (spc, model) =>
        {
            if (model is null)
            {
                return;
            }

            var source = GenerateSource(model.Value);
            spc.AddSource($"{model.Value.TypeName}SheetBuilderExtensions.g.cs", source);
        });
    }

    static ModelInfo? GetModelInfo(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var properties = GetProperties(type).ToImmutableArray();

        if (properties.Length == 0)
        {
            return null;
        }

        return new ModelInfo(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            properties);
    }

    static IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol type) =>
        GetPropertiesRecursive(type, ImmutableArray<string>.Empty);

    static IEnumerable<PropertyInfo> GetPropertiesRecursive(INamedTypeSymbol type, ImmutableArray<string> parentPath)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol property)
            {
                continue;
            }

            if (property.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (property.GetMethod is null)
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.IgnoreAttribute"))
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.SplitAttribute") ||
                HasAttribute(property.Type, "Excelsior.SplitAttribute"))
            {
                if (property.Type is INamedTypeSymbol namedType)
                {
                    var newPath = parentPath.Add(property.Name);
                    foreach (var nested in GetPropertiesRecursive(namedType, newPath))
                    {
                        yield return nested;
                    }
                }

                continue;
            }

            var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var accessPath = parentPath.IsEmpty
                ? property.Name
                : string.Join(".", parentPath.Add(property.Name));

            yield return new PropertyInfo(property.Name, propertyType, accessPath);
        }
    }

    static bool HasAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fullName);

    static bool HasAttribute(ITypeSymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fullName);

    static string GenerateSource(ModelInfo model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Excelsior;");
        sb.AppendLine();
        sb.AppendLine($"public static class {model.TypeName}SheetBuilderExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var prop = model.Properties[i];
            if (i > 0)
            {
                sb.AppendLine();
            }

            var prefix = prop.Name;
            var propType = prop.TypeFullName;
            var modelType = model.TypeFullName;
            var access = prop.AccessPath;

            // Column
            sb.AppendLine($"    public static ISheetBuilder<{modelType}, TStyle> {prefix}Column<TStyle>(");
            sb.AppendLine($"        this ISheetBuilder<{modelType}, TStyle> builder,");
            sb.AppendLine($"        System.Action<ColumnConfig<TStyle, {modelType}, {propType}>> configuration)");
            sb.AppendLine($"        => builder.Column(_ => _.{access}, configuration);");

            // HeadingText
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}HeadingText<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            sb.AppendLine($"        => builder.HeadingText(_ => _.{access}, value);");

            // Order
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}Order<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)");
            sb.AppendLine($"        => builder.Order(_ => _.{access}, value);");

            // Width
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}Width<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)");
            sb.AppendLine($"        => builder.Width(_ => _.{access}, value);");

            // HeadingStyle
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}HeadingStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Action<TStyle> value)");
            sb.AppendLine($"        => builder.HeadingStyle(_ => _.{access}, value);");

            // CellStyle (with model)
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}CellStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Action<TStyle, {modelType}, {propType}> value)");
            sb.AppendLine($"        => builder.CellStyle(_ => _.{access}, value);");

            // Format
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}Format<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            sb.AppendLine($"        => builder.Format(_ => _.{access}, value);");

            // NullDisplay
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}NullDisplay<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            sb.AppendLine($"        => builder.NullDisplay(_ => _.{access}, value);");

            // IsHtml
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}IsHtml<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)");
            sb.AppendLine($"        => builder.IsHtml(_ => _.{access});");

            // Render (with model)
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}Render<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Func<{modelType}, {propType}, string?> value)");
            sb.AppendLine($"        => builder.Render(_ => _.{access}, value);");

            // Filter
            sb.AppendLine();
            sb.AppendLine($"    public static void {prefix}Filter<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)");
            sb.AppendLine($"        => builder.Filter(_ => _.{access});");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}

record struct ModelInfo(
    string TypeFullName,
    string TypeName,
    ImmutableArray<PropertyInfo> Properties);

record struct PropertyInfo(
    string Name,
    string TypeFullName,
    string AccessPath);
