namespace Excelsior.SourceGenerator;

[Generator]
public class SheetBuilderExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
            "Excelsior.SheetModelAttribute",
            (node, _) => node is TypeDeclarationSyntax,
            (context, _) => GetModelInfo(context));

        context.RegisterSourceOutput(
            models,
            (productionContext, model) =>
        {
            if (model is null)
            {
                return;
            }

            var source = GenerateSource(model.Value);
            productionContext.AddSource($"{model.Value.TypeName}SheetBuilderExtensions.g.cs", source);
        });
    }

    static ModelInfo? GetModelInfo(GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var properties = new EquatableArray<PropertyInfo>(GetProperties(type).ToImmutableArray());

        if (properties.Length == 0)
        {
            return null;
        }

        return new ModelInfo(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            properties);
    }

    static IEnumerable<PropertyInfo> GetProperties(INamedTypeSymbol type) =>
        GetPropertiesRecursive(type, ImmutableArray<string>.Empty);

    static IEnumerable<PropertyInfo> GetPropertiesRecursive(INamedTypeSymbol type, ImmutableArray<string> parentPath)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol property)
            {
                continue;
            }

            if (property.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (property.GetMethod is null)
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.IgnoreAttribute"))
            {
                continue;
            }

            if (HasAttribute(property, "Excelsior.SplitAttribute") ||
                HasAttribute(property.Type, "Excelsior.SplitAttribute"))
            {
                if (property.Type is INamedTypeSymbol namedType)
                {
                    var newPath = parentPath.Add(property.Name);
                    foreach (var nested in GetPropertiesRecursive(namedType, newPath))
                    {
                        yield return nested;
                    }
                }

                continue;
            }

            var propertyType = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var accessPath = parentPath.IsEmpty
                ? property.Name
                : string.Join(".", parentPath.Add(property.Name));

            yield return new(property.Name, propertyType, accessPath);
        }
    }

    static bool HasAttribute(ISymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fullName);

    static bool HasAttribute(ITypeSymbol symbol, string fullName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fullName);

    static string GenerateSource(ModelInfo model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Excelsior;");
        builder.AppendLine();
        builder.AppendLine($"public static class {model.TypeName}SheetBuilderExtensions");
        builder.AppendLine("{");

        for (var i = 0; i < model.Properties.Array.Length; i++)
        {
            if (i > 0)
            {
                builder.AppendLine();
            }

            var (prefix, propType, access) = model.Properties[i];
            var modelType = model.TypeFullName;

            // Column
            builder.AppendLine($"    public static ISheetBuilder<{modelType}, TStyle> {prefix}Column<TStyle>(");
            builder.AppendLine($"        this ISheetBuilder<{modelType}, TStyle> builder,");
            builder.AppendLine($"        System.Action<ColumnConfig<TStyle, {modelType}, {propType}>> configuration)");
            builder.AppendLine($"        => builder.Column(_ => _.{access}, configuration);");

            // HeadingText
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}HeadingText<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            builder.AppendLine($"        => builder.HeadingText(_ => _.{access}, value);");

            // Order
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}Order<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)");
            builder.AppendLine($"        => builder.Order(_ => _.{access}, value);");

            // Width
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}Width<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, int? value)");
            builder.AppendLine($"        => builder.Width(_ => _.{access}, value);");

            // HeadingStyle
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}HeadingStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Action<TStyle> value)");
            builder.AppendLine($"        => builder.HeadingStyle(_ => _.{access}, value);");

            // CellStyle (with model)
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}CellStyle<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Action<TStyle, {modelType}, {propType}> value)");
            builder.AppendLine($"        => builder.CellStyle(_ => _.{access}, value);");

            // Format
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}Format<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            builder.AppendLine($"        => builder.Format(_ => _.{access}, value);");

            // NullDisplay
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}NullDisplay<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, string value)");
            builder.AppendLine($"        => builder.NullDisplay(_ => _.{access}, value);");

            // IsHtml
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}IsHtml<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)");
            builder.AppendLine($"        => builder.IsHtml(_ => _.{access});");

            // Render (with model)
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}Render<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder, System.Func<{modelType}, {propType}, string?> value)");
            builder.AppendLine($"        => builder.Render(_ => _.{access}, value);");

            // Filter
            builder.AppendLine();
            builder.AppendLine($"    public static void {prefix}Filter<TStyle>(this ISheetBuilder<{modelType}, TStyle> builder)");
            builder.AppendLine($"        => builder.Filter(_ => _.{access});");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }
}
