global using System.Data;
global using Syncfusion.XlsIO;
global using Excelsior;
global using ExcelsiorSyncfusion;
global using Syncfusion.Drawing;
global using Syncfusion.Office;
global using Syncfusion.XlsIO.Implementation;
global using Syncfusion.XlsIO.Implementation.Collections;
global using Sheet = Syncfusion.XlsIO.IWorksheet;
global using Style = Syncfusion.XlsIO.IStyle;
global using Range = Syncfusion.XlsIO.IRange;
