global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Linq.Expressions;
global using System.Runtime.CompilerServices;
global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.Packaging;
global using DocumentFormat.OpenXml.Spreadsheet;
global using Excelsior;
global using OpenXmlHtml;
global using Cell = DocumentFormat.OpenXml.Spreadsheet.Cell;
global using CellStyle = Excelsior.CellStyle;
global using Color = DocumentFormat.OpenXml.Spreadsheet.Color;
global using Column = DocumentFormat.OpenXml.Spreadsheet.Column;
global using Font = DocumentFormat.OpenXml.Spreadsheet.Font;